### ISSUE TITLE
Сделать страницу списка всех пользователей сайта

### ISSUE THREAD

**Issue by fks213** [fks213/project#6]
Можно прикрепить к поиску и сделать права на доступ будет ли там выводиться страница или нет

**Comment by Nemec25** [comment]
Ну можно сделать так, что если поля пустые, то выводить будет всех пользователей, а зачем делать права? Достаточно прав на просмотр содержания страницы

**Comment by Nemec25** [comment]
Сделал так, что если ввести пустые поля в поиске, тогда покажутся все пользователи, issue можно закрыть.
